// <auto-generated />
namespace TP_PWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class login12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(login12));
        
        string IMigrationMetadata.Id
        {
            get { return "202001031145162_login12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
